# Generated by Django 4.0.6 on 2022-07-19 01:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sub_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Grupo')),
            ],
            options={
                'verbose_name': 'Sub Grupo',
                'verbose_name_plural': 'Sub Grupos',
                'ordering': ('sub_group',),
            },
        ),
    ]
