# Generated by Django 4.0.6 on 2022-07-19 01:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('stock', models.IntegerField(verbose_name='Estoque atual')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='estoque mínimo')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='products.group', verbose_name='Grupo')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_groups', to='products.subgroup', verbose_name='Sub Groupo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('product',),
            },
        ),
    ]
