# Generated by Django 4.0.6 on 2022-07-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='products.group',
        ),
        migrations.AlterModelTable(
            name='subgroup',
            table='products.sub_group',
        ),
    ]
