# Generated by Django 4.0.6 on 2022-07-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_company_product_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('und', 'Unidade'), ('b', 'Caixa'), ('g', 'Grama'), ('kg', 'Quilograma')], default='und', max_length=3),
        ),
    ]
