# Generated by Django 4.0.6 on 2022-07-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_table'),
        ('users', '0002_profile'),
        ('products', '0008_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.company', verbose_name='Companhia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.profile', verbose_name='Usuário'),
        ),
    ]
