# Generated by Django 4.0.6 on 2022-07-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='products.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('und', 'Unidade'), ('b', 'Caixa'), ('g', 'Grama'), ('kg', 'Quilograma')], default='und', max_length=3, verbose_name='Unidade'),
        ),
    ]
