# Generated by Django 4.0.6 on 2022-07-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_cnpj'),
        ('products', '0013_alter_product_group_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.company', verbose_name='Companhia'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_groups', to='core.company', verbose_name='Companhia'),
        ),
    ]
