version: "3.9"
services:
  growpier:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: growpier
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - .env  
    networks: 
      - digitaltree
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    container_name: digitaltree-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks: 
      - digitaltree
  
  proxy:
    build:
      context: ./docker/proxy
    container_name: digitaltree-proxy
    restart: always
    depends_on:
      - digitaltree
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
    networks: 
      - digitaltree

networks:
  digitaltree:
    name: digitaltree
    driver: bridge

volumes:
  postgres-data:
  static-data: