# Generated by Django 4.0.6 on 2022-07-19 22:48

import apps.core.models
from django.db import migrations, models
import localflavor.br.models
import utils.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=250, verbose_name='Empresa')),
                ('cnpj', localflavor.br.models.BRCNPJField(default='', max_length=18, verbose_name='CNPJ')),
                ('postal_code', localflavor.br.models.BRPostalCodeField(default='', max_length=9, verbose_name='CEP')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Endereço')),
                ('cell_phone', models.CharField(blank=True, default='', max_length=250, verbose_name='Telefone Celular')),
                ('number', models.CharField(default='', max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Complemento')),
                ('district', models.CharField(default='', max_length=100, verbose_name='Bairro')),
                ('state', localflavor.br.models.BRStateField(default='', max_length=2, verbose_name='Estado')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Cidade')),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to=apps.core.models.upload_photo_company, validators=[utils.forms.photo_size], verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Companhia',
                'verbose_name_plural': 'Companhias',
                'ordering': ('company',),
            },
        ),
    ]
