# Generated by Django 4.0.6 on 2022-07-21 13:09

import apps.core.models
from django.db import migrations, models
import utils.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='photo_profile',
            field=models.ImageField(default='profile_default.png', null=True, upload_to=apps.core.models.upload_photo_company, validators=[utils.forms.photo_size], verbose_name='Foto'),
        ),
    ]
