# Generated by Django 4.0.6 on 2022-07-25 21:48

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_is_active_alter_company_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(default='', max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
