# Generated by Django 4.0.6 on 2022-07-19 23:32

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.forms
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_table'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to=apps.users.models.upload_photo_company, validators=[utils.forms.photo_size], verbose_name='Foto')),
                ('aboult', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='companies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'users.profile',
                'ordering': ('user',),
            },
        ),
    ]
