# Generated by Django 4.0.6 on 2022-07-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_table'),
        ('users', '0003_alter_profile_company_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to='core.company', verbose_name='Companhia'),
        ),
    ]
