# Generated by Django 4.0.6 on 2022-07-20 00:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_company_alter_product_profile'),
        ('users', '0002_profile'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviment_profiles', to='users.profile', verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Iten',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('stock', models.IntegerField(verbose_name='Estoque')),
                ('moviment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviments', to='stocks.moviment', verbose_name='Movimento')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iten_products', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Iten',
                'verbose_name_plural': 'Itens',
                'db_table': 'stocks.iten',
                'ordering': ('-id',),
            },
        ),
    ]
