# Generated by Django 4.0.6 on 2022-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rename_unit_moviment_moviment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iten',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='moviment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
